RP2040_BOOTLOADER_DOUBLE_TAP_RESET = yes

OLED_ENABLE = yes
ENCODER_MAP_ENABLE = yes
CONSOLE_ENABLE = yes

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
REPEAT_KEY_ENABLE = yes

NKRO_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
AUTOCORRECT_ENABLE = yes
CAPS_WORD_ENABLE = yes
OS_DETECTION_ENABLE = yes